name: env_gradient
channels:
  - conda-forge
dependencies:
  - python==3.8.*
  - pip
  - ipython
  - jupyter
  - numpy
  - matplotlib
  - joblib
  - pytest
  - sphinx
  - numpydoc
  - nbsphinx
  - pip:
    - notebook
    - jinja2==3.0.3  # otherwise error when compiling the documentation